name: C++ CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Install CMake
    - name: Install CMake
      uses: actions/awslabs/setup-cmake@v1
      with:
        cmake-version: latest # Specify the desired version of CMake

    # Set up C++ compiler
    - name: Set up C++ compiler
      uses: actions/setup-cpp@v2
      with:
        compiler: gcc # or "clang"

    # Configure and build the CMake project
    - name: Configure CMake project
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build .

    # Run tests
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
