name: C++ CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Проверка кода
      - name: Checkout code
        uses: actions/checkout@v3

      # Сборка проекта
      - name: Configure CMake
        run: cmake . -B build

      - name: Build project
        run: cmake --build build

      # Запуск тестов
      - name: Run tests
        run: ctest --test-dir build --output-on-failure
